# Generated by Django 5.1.3 on 2025-01-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
