# Generated by Django 5.1.3 on 2025-01-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_department_options_remove_category_image_and_more'),
    ]

    operations = [
    ]
